# Trusted Platform Configuration File

debug: true
debug-secrets: true
platform-dir: trusted-data
config-dir: trusted-data/etc
log-dir: trusted-data/log
listen: localhost
hostname: server1
domain: trusted-platform.local
hostmaster: root@trusted-platform.local
pin-seal-policy: true


acme:
  # ACME challenges supported by the server
  challenges:
    - device-01
    - device-attest-01
    - dns-01
    - endorse-01
    - http-01
    # Custom http-01 challenges that listen
    # on ports 8080 and 8081. These challenges
    # use the custom httpx challenge which uses
    # the port number defined in this challenge
    # name to serve the http-01 challenge on a 
    # custom, user-defined port. Enter any valid
    # port number following http- to have the http-01
    # challenge served on that port.
    - http-8080
    - http-8081
    - device-8080
    - device-8081

attestation:
  allow-open-enrollment: true
  allow-attestor-self-ca: true
  tls-port: 8082
  insecure-port: 8083
  insecure-skip-verify: false
  allowed-verifiers:
    - __VERIFIER_CA__
  quote-pcrs: 23


datastore:
  backend: fs
  consistency-level: local
  home: trusted-data/datastore
  read-buffer-size: 50
  serializer: json


tpm:
  device: /dev/tpmrm0
  simulator: true
  encrypt-sessions: false
  entropy: false
  hash: SHA-256
  ek:
    debug: true
    handle: 0x81010001
    hash: SHA-256
    password:
    rsa:
      size: 2048
  ssrk:
    debug: true
    handle: 0x81000001
    hierarchy-auth: 
    password: 
    platform-policy: true 
    rsa:
      size: 2048
  iak:
    auth:
    debug: true
    hash: SHA-256
    handle: 0x81010002
    password: 
    # platform-policy: true 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  idevid:
    model: trusted-platform-edge
    serial: att-tp-e001
    cert-handle: 0x01C90000
    debug: true
    handle: 0x81020000
    hash: SHA-256
    pad: true
    password: 
    # platform-policy: true 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  platform-pcr: 23
  file-integrity:
    - ./
  keystore:
    srk-handle: 0x81000002
    srk-auth: 123456
    platform-policy: true


certificate-authority:
  acme-server: https://localhost:8443/api/v1
  platform-ca: 1
  auto-import-issuing-ca: true
  system-cert-pool: false
  default-validity: 365
  default-idevid-cn: default-device-id
  sans-include-localhost: true
  require-password: true
  quantum-safe: true
  identity:
    - 
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000003
          srk-auth: 123456
          platform-policy: true
      keys:
        # PKCS #8 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
            scheme: 
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P-256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

      valid: 50
      subject:
        cn: server1-root-ca.trusted-platform.local
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns: 
          - root-ca.trusted-platform.local
          - root-ca
          - root-ca.localdomain
          - root-ca.dev.trusted-platform.local
        ips:
          - 127.0.0.1
        email:
          - root@localhost
          - root@localhost.localdomain

    - # Intermediate Certificate Authority
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000004
          srk-auth: 123456
          platform-policy: true
      keys:
        - # PKCS #8 RSA w/ PSS
          algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P-256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true
      valid: 10
      subject:
        cn: server1-intermediate-ca.trusted-platform.local
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns:
          - intermediate-ca.trusted-platform.local
          - intermediate-ca
          - intermediate-ca.localdomain
        ips:
          - 127.0.0.1
        email:
          - root@localhost
          - root@localhost.localdomain

webservice:
  home: public_html
  terms-of-service: /tos.html
  port: 8080
  tls-port: 8443
  jwt:
    expiration: 525960
    # algorithm: PS256
    issuer: my_org_id
  webauthn:
    display-name: Trusted Platform
    id: localhost
    origins:
      - https://localhost
      - https://localhost:8443
      - http://localhost:3000
  key:
    # PKCS #8 RSA w/ PSS
    algorithm: RSA
    debug: true
    hash: SHA-256
    password:
    platform-policy:
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
    store: pkcs8
    #
    # algorithm: ECDSA
    # ecc:
    #   curve: P-256
    # signature-algorithm: ECDSA-SHA256
    # hash: SHA-256
    # store: pkcs8
    # password: 123456
    # platform-policy: true
    # debug: true
    #
    # algorithm: Ed25519
    # ecc:
    #   curve: P-256
    # signature-algorithm: Ed25519
    # hash: SHA-256
    # store: pkcs8
    # password: 123456
    # platform-policy: true
    # debug: true
  certificate:
    valid: 365
    subject:
      cn: server1.trusted-platform.local
      organization: Trusted Platform
      country: US
      province: Kernel
      locality: Hypervisor
      address: 123 Example Street
      postal-code: 12345
    sans:
      ips:
        - 127.0.0.1
      email:
        - root@localhost
        - root@localhost.localdomain


# Argon2 Password Hashing
# https://github.com/P-H-C/phc-winner-argon2
# https://pkg.go.dev/golang.org/x/crypto/argon2
argon2:
  memory: 1
  iterations: 1
  parallelism: 1
  saltLen: 16
  keyLen: 32
