# Trusted Platform Configuration File


debug: true
debug-secrets: true
platform-dir: trusted-data
config-dir: trusted-data/etc
log-dir: trusted-data/log
listen: localhost
hostname: node1
domain: example.com
hostmaster: root@example.com
pin-seal-policy: true


attestation:
  allow-open-enrollment: true
  allow-attestor-self-ca: true
  tls-port: 8082
  insecure-port: 8083
  insecure-skip-verify: false
  allowed-verifiers:
    - __VERIFIER_CA__
  quote-pcrs: 23


tpm:
  device: /dev/tpmrm0
  simulator: true
  encrypt-sessions: true
  entropy: false
  hash: SHA-256
  ek:
    debug: true
    handle: 0x81010001
    hash: SHA-256
    password:
    rsa:
      size: 2048
  ssrk:
    debug: true
    handle: 0x81000001
    hierarchy-auth: 
    password: 
    platform-policy: true 
    rsa:
      size: 2048
  iak:
    cn: device-id-001
    debug: true
    hash: SHA-256
    handle: 0x81010002
    password: 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  idevid:
    model: trusted-platform-edge
    serial: att-tp-e001
    cert-handle: 0x01C90000
    cn: device-id-001
    debug: true
    handle: 0x81020000
    hash: SHA-256
    pad: true
    password: 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  platform-pcr: 23
  file-integrity:
    - .
  keystore:
    srk-handle: 0x81000002
    srk-auth: 123456
    platform-policy: true


certificate-authority:
  platform-ca: 1
  auto-import-issuing-ca: true
  system-cert-pool: false
  issued-valid: 365
  sans-include-localhost: true
  require-password: true
  password-policy: inherit
  retain-revoked-certificates: true
  identity:
    - 
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000003
          srk-auth: 123456
          platform-policy: true
      keys:
        -
        # PKCS #8 RSA w/ PSS
          algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true
        
        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true
        
        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

      valid: 50
      subject:
        cn: root-ca.example.com
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns: 
          - root-ca.example.com
          - root-ca
          - root-ca.localdomain
          - root-ca.dev.example.com
        ips:
          - 127.0.0.1
        email:
          - root@localhost
          - root@localhost.localdomain
    - # Intermediate Certificate Authority
      home: ca
      random-source: tpm2
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000004
          srk-auth: 123456
          platform-policy: true

      keys:
        -
        # PKCS #8 RSA w/ PSS
          algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true
        
        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true
        
        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

      valid: 10
      subject:
        cn: intermediate-ca.example.com
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns:
          - intermediate-ca.example.com
          - intermediate-ca
          - intermediate-ca.localdomain
        ips:
          - 127.0.0.1
        email:
          - root@localhost
          - root@localhost.localdomain


webservice:
  port: 8080
  tls-port: 8443
  jwt-expiration: 525960
  key:
    # PKCS #8 RSA w/ PSS
    algorithm: RSA
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
    hash: SHA-256
    store: pkcs8
    password: 123456
    platform-policy: true
    default: true
    debug: true
    #
    # algorithm: ECDSA
    # ecc:
    #   curve: P256
    # signature-algorithm: ECDSA-SHA256
    # hash: SHA-256
    # store: pkcs8
    # password: 123456
    # platform-policy: true
    # debug: true
    #
    # algorithm: Ed25519
    # ecc:
    #   curve: P256
    # signature-algorithm: Ed25519
    # hash: SHA-256
    # store: pkcs8
    # password: 123456
    # platform-policy: true
    # debug: true
  certificate:
    valid: 365
    subject:
      cn: www.example.com
      organization: Trusted Platform
      country: US
      province: Kernel
      locality: Hypervisor
      address: 123 Example Street
      postal-code: 12345
    sans:
      dns:
        - www.example.com
        - localhost
        - localhost.localdomain
      ips:
        - 127.0.0.1
      email:
        - root@localhost
        - root@localhost.localdomain


argon2:
  memory: 1
  iterations: 1
  parallelism: 1
  saltLen: 16
  keyLen: 32
