# Trusted Platform Configuration File

debug: true
debug-secrets: true
platform-dir: trusted-data
config-dir: trusted-data/etc
log-dir: trusted-data/log
domain: edge01.dev.trusted-platform.local
hostmaster: hostmaster@edge01.dev.trusted-platform.local
pin-seal-policy: true


acme:
  client:
    directory: https://dev.trusted-platform.local/api/v1/acme/directory
    enrollment-challenge: device-8081
    request-server-bundle: true
    account:
      email: hostmaster@edge01.dev.trusted-platform.local
      key:
        # PKCS #8 RSA w/ PSS
        algorithm: RSA
        cn: acme-account
        debug: true
        hash: SHA-256
        password: 123456
        platform-policy: true
        rsa:
          size: 2048
        signature-algorithm: SHA256-RSAPSS
        store: pkcs8
      register: true


datastore:
  backend: AFERO_FS
  consistency-level: local
  home: trusted-data/datastore
  read-buffer-size: 50
  serializer: json


tpm:
  device: /dev/tpmrm0
  simulator: true
  encrypt-sessions: false
  entropy: false
  hash: SHA-256
  ek:
    debug: true
    handle: 0x81010001
    hash: SHA-256
    password:
    rsa:
      size: 2048
  ssrk:
    debug: true
    handle: 0x81000001
    hierarchy-auth: 
    password: 
    platform-policy: true 
    rsa:
      size: 2048
  iak:
    auth:
    debug: true
    hash: SHA-256
    handle: 0x81010002
    password: 
    # platform-policy: true 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  idevid:
    model: trusted-edge
    serial: att-tp-e002
    cert-handle: 0x01C90000
    debug: true
    handle: 0x81020000
    hash: SHA-256
    pad: true
    password: 
    # platform-policy: true 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  platform-pcr: 23
  file-integrity:
    - ./
  keystore:
    srk-handle: 0x81000002
    srk-auth: 123456
    platform-policy: true


certificate-authority:
  acme-server: https://edge01.dev.trusted-platform.local:8443/api/v1
  platform-ca: 1
  auto-import-issuing-ca: true
  system-cert-pool: false
  default-validity: 365
  default-idevid-cn: default-device-id
  sans-include-localhost: true
  require-password: true
  quantum-safe: true
  identity:
    - 
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000003
          srk-auth: 123456
          platform-policy: true
      keys:
        # PKCS #8 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
            scheme: 
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P-256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

      valid: 50
      subject:
        cn: root-ca.edge01.dev.trusted-platform.local
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns: 
          - root-ca.edge01.dev.trusted-platform.local
        email:
          - hostmaster@edge01.dev.trusted-platform.local

    - # Intermediate Certificate Authority
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000004
          srk-auth: 123456
          platform-policy: true
      keys:
        - # PKCS #8 RSA w/ PSS
          algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P-256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true
      valid: 10
      subject:
        cn: ca01.edge01.dev.trusted-platform.local
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns:
          - ca01.edge01.dev.trusted-platform.local
        email:
          - hostmaster@edge01.dev.trusted-platform.local


webservice:
  home: public_html
  terms-of-service: /tos.html
  port: 8080
  tls-port: 8443
  index: index.html
  jwt:
    expiration: 525960
    issuer: edge01.dev.trusted-platform.local
  webauthn:
    display-name: Trusted Platform (Dev)
    id: edge01.dev.trusted-platform.local
    origins:
      - https://edge01.dev.trusted-platform.local
      - https://edge01.dev.trusted-platform.local:8080
  key:
    algorithm: ECDSA
    ecc:
      curve: P-256
    signature-algorithm: ECDSA-SHA256
    hash: SHA-256
    store: pkcs8
    password: 123456
    platform-policy: true
    debug: true
  certificate:
    acme:
      challenge: http-01
      renew: 15
    subject:
      cn: edge01.dev.trusted-platform.local
      organization: Automate The Things, LLC
      country: US
      province: Florida
      locality: West Palm Beach
      address: 123 Automation Street
      postal-code: 12345
    sans:
      dns:
        - edge01.dev.trusted-platform.local
      email:
        - hostmaster@edge01.dev.trusted-platform.local
  virtual-hosts:
    - home: api.edge01.dev.trusted-platform.local
      index: index.html
      hosts:
        - api.edge01.dev.trusted-platform.local
        - vhost1.edge01.dev.trusted-platform.local
        - vhost2.edge01.dev.trusted-platform.local
      key:
        algorithm: ECDSA
        ecc:
          curve: P-256
        signature-algorithm: ECDSA-SHA256
        hash: SHA-256
        store: pkcs8
        password: 123456
        platform-policy: true
        debug: true
      certificate:
        acme:
          challenge: http-01
          renew: 15
        valid: 365
        subject:
          cn: api.edge01.dev.trusted-platform.local
          organization: Automate The Things, LLC
          country: US
          province: Kernel
          locality: Hypervisor
          address: 456 Virtual Street
          postal-code: 67890
        sans:
          dns:
            - api.edge01.dev.trusted-platform.local
            - vhost1.edge01.dev.trusted-platform.local
            - vhost2.edge01.dev.trusted-platform.local
          email:
            - hostmaster@edge01.dev.trusted-platform.local
    - home: edge01.dev.trusted-platform.local
      index: index.html
      hosts:
        - edge01.dev.trusted-platform.local
        - edge01.dev.trusted-platform.local
      proxy:
        backends:
          - http://192.168.200.10:8080
      key:
        algorithm: ECDSA
        ecc:
          curve: P-256
        signature-algorithm: ECDSA-SHA256
        hash: SHA-256
        store: pkcs8
        password: 123456
        platform-policy: true
        debug: true
      certificate:
        acme:
          challenge: http-01
          renew: 15
        valid: 365
        subject:
          cn: edge01.dev.trusted-platform.local
          organization: Automate The Things, LLC
          country: US
          province: Kernel
          locality: Hypervisor
          address: 456 Virtual Street
          postal-code: 67890
        sans:
          dns:
            - edge01.dev.trusted-platform.local
          email:
            - hostmaster@edge01.dev.trusted-platform.local


# Argon2 Password Hashing
# https://github.com/P-H-C/phc-winner-argon2
# https://pkg.go.dev/golang.org/x/crypto/argon2
argon2:
  memory: 65536
  iterations: 3
  parallelism: 2
  saltLen: 16
  keyLen: 32
