# Trusted Platform Configuration File (dev client)

# Configuration for the Trusted Platform
# dev.trusted-platform.io environment, 
# running the platform software as a client
# connected to an "Enterprise Platform" running
# the platform software as a server. This client
# is integrated with Let's Encrypt staging to 
# cross-sign public TLS certifictes issued by the
# Enterprise CA.

# With this configuration, the client performs
# the following steps:

# 1. Start-up using TPM simulator
# 2. Provision the base platform, create local CA
#    and platform keys. Start the local CA.
# 3. Request an EK certificate via ACME endorse-01.
# 4. Perform device enrollment with the Enterprise CA
#    via ACME enroll-01. The server creates a device
#    record for the client, storing it's TCG-CSR-IDEVID
#    attestation data and generates DNS entries so the
#    device is discoverable and ready for communication
#    on the Enterprise Network. The device is issued an 
#    IAK and IDevID certificate. The IDevID is used to
#    authenticate the device to the network going forward,
#    and can also be used as a permanent-identifier in 
#    privacy focused environments where binding to the EK
#    serial is undesirable.
# 5. Request a TLS certificate from the Enterprise / Privacy
#    CA via ACME device-attest-01 and cross-sign the certificate
#    with Let's Encrypt staging for public use. This allows
#    clients / browsers to chain up to either the Enterprise CA
#    or Let's Encrypt Root certificates (or both) depending on the
#    certificates trusted by that client / browser. This allows
#    internal services who trust the Enterprise CA to chain up to
#    the Enterprise / Privacy CA using a certificate that contains
#    TCG and Trusted Platform specific OIDs, while public clients
#    who may not trust it, or interested in the "Trust OIDs" to
#    chain up to Let's Encrypt, who they do trust. Cross-signing
#    features work with any ACME RFC 8555 compliant server.
# 6. Start the client web services using the issued TLS certificates

debug: true
debug-secrets: true
platform-dir: trusted-data
config-dir: trusted-data/etc
log-dir: trusted-data/log
domain: dashboard.dev.trusted-platform.io
hostmaster: hostmaster@dashboard.dev.trusted-platform.io
pin-seal-policy: true


acme:
  client:
    directory: https://dev.trusted-platform.io/api/v1/acme/directory
    enrollment:
      challenge: enroll-8081
      ip: ${PREFERRED_IP}
    request-server-bundle: true
    account:
      email: hostmaster@dashboard.dev.trusted-platform.io
      key:
        # PKCS #8 RSA w/ PSS
        algorithm: RSA
        cn: acme-account
        debug: true
        hash: SHA-256
        password: 123456
        platform-policy: true
        rsa:
          size: 2048
        signature-algorithm: SHA256-RSAPSS
        store: pkcs8
      register: true


datastore:
  backend: AFERO_FS
  consistency-level: local
  home: trusted-data/datastore
  read-buffer-size: 50
  serializer: json


tpm:
  device: /dev/tpmrm0
  simulator: true
  encrypt-sessions: false
  entropy: false
  hash: SHA-256
  ek:
    debug: true
    handle: 0x81010001
    hash: SHA-256
    password:
    rsa:
      size: 2048
  ssrk:
    debug: true
    handle: 0x81000001
    hierarchy-auth: 
    password: 
    platform-policy: true 
    rsa:
      size: 2048
  iak:
    auth:
    debug: true
    hash: SHA-256
    handle: 0x81010002
    password: 
    # platform-policy: true 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  idevid:
    model: edge
    serial: mfg-serial-e002
    cert-handle: 0x01C90000
    debug: true
    handle: 0x81020000
    hash: SHA-256
    pad: true
    password: 
    # platform-policy: true 
    rsa:
      size: 2048
    signature-algorithm: SHA256-RSAPSS
  platform-pcr: 23
  file-integrity:
    - ./
  keystore:
    srk-handle: 0x81000002
    srk-auth: 123456
    platform-policy: true


certificate-authority:
  platform-ca: 1
  auto-import-issuing-ca: true
  system-cert-pool: false
  default-validity: 365
  default-idevid-cn: default-device-id
  sans-include-localhost: true
  require-password: true
  quantum-safe: true
  identity:
    - 
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000003
          srk-auth: 123456
          platform-policy: true
      keys:
        # PKCS #8 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
            scheme: 
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P-256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

      valid: 50
      subject:
        cn: root-ca.dashboard.dev.trusted-platform.io
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns: 
          - root-ca.dashboard.dev.trusted-platform.io
        email:
          - hostmaster@dashboard.dev.trusted-platform.io

    - # Intermediate Certificate Authority
      keystores:
        pkcs8:
          platform-policy: true
        pkcs11:
          library: /usr/local/lib/softhsm/libsofthsm2.so
          config: trusted-data/etc/softhsm.conf
          slot: 0
          label: SoftHSM
          pin: 123456
          platform-policy: true
        tpm2:
          srk-handle: 0x81000004
          srk-auth: 123456
          platform-policy: true
      keys:
        - # PKCS #8 RSA w/ PSS
          algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 RSA w/ PSS
        - algorithm: RSA
          rsa:
            size: 2048
          signature-algorithm: SHA256-RSAPSS
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #11 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: pkcs11
          password: 123456
          platform-policy: true
          debug: true

        # TPM 2.0 ECDSA
        - algorithm: ECDSA
          ecc:
            curve: P-256
          signature-algorithm: ECDSA-SHA256
          hash: SHA-256
          store: tpm2
          password: 123456
          platform-policy: true
          debug: true

        # PKCS #8 Ed25519
        - algorithm: Ed25519
          ecc:
            curve: P-256
          signature-algorithm: Ed25519
          hash: SHA-256
          store: pkcs8
          password: 123456
          platform-policy: true
          debug: true
      valid: 10
      subject:
        cn: ca01.dashboard.dev.trusted-platform.io
        organization: Trusted Platform
        country: US
        province: Kernel
        locality: Hypervisor
        address: 123 Example Street
        postal-code: 12345
      sans:
        dns:
          - ca01.dashboard.dev.trusted-platform.io
        email:
          - hostmaster@dashboard.dev.trusted-platform.io


webservice:
  home: public_html
  port: 8081
  tls-port: 8444
  index: index.html
  jwt:
    expiration: 525960
    issuer: dashboard.dev.trusted-platform.io
  webauthn:
    display-name: Trusted Platform (Dev)
    #id: dashboard.dev.trusted-platform.io
    id: localhost
    origins:
      - https://dashboard.dev.trusted-platform.io
      - https://dashboard.dev.trusted-platform.io:8443
      - http://dashboard.dev.trusted-platform.io:8080
      - https://localhost
      - http://localhost
      - http://localhost:8080
      - https://localhost:8443
      - http://localhost:3000      
  cors:
    allowed-origins:
      - https://dashboard.dev.trusted-platform.io
      - http://dashboard.dev.trusted-platform.io
      - https://localhost
      - http://localhost
      - http://localhost:8080
      - https://localhost:8443
      - http://localhost:3000
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true
  key:
    algorithm: ECDSA
    ecc:
      curve: P-256
    signature-algorithm: ECDSA-SHA256
    hash: SHA-256
    store: pkcs8
    password: 123456
    platform-policy: true
    debug: true
  certificate:
    acme:
      challenge: device-attest-01
      renew: 15
      cross-sign:
        directory: https://acme-staging-v02.api.letsencrypt.org/directory
        challenge: http-01
    subject:
      cn: dashboard.dev.trusted-platform.io
      organization: Automate The Things, LLC
      country: US
      province: Florida
      locality: West Palm Beach
      address: 123 Automation Street
      postal-code: 12345
    sans:
      dns:
        - dashboard.dev.trusted-platform.io
      email:
        - hostmaster@dashboard.dev.trusted-platform.io
  virtual-hosts:

    # Virtual Host for API gateway running on the client
    - home: api.dashboard.dev.trusted-platform.io
      index: index.html
      hosts:
        - api.dashboard.dev.trusted-platform.io
        - vhost1.dashboard.dev.trusted-platform.io
        - vhost2.dashboard.dev.trusted-platform.io
      key:
        algorithm: ECDSA
        ecc:
          curve: P-256
        signature-algorithm: ECDSA-SHA256
        hash: SHA-256
        store: pkcs8
        password: 123456
        platform-policy: true
        debug: true
      certificate:
        acme:
          challenge: http-01
          renew: 15
          cross-sign:
            directory: https://acme-staging-v02.api.letsencrypt.org/directory
            challenge: http-01
        valid: 365
        subject:
          cn: api.dashboard.dev.trusted-platform.io
          organization: Automate The Things, LLC
          country: US
          province: Kernel
          locality: Hypervisor
          address: 456 Virtual Street
          postal-code: 67890
        sans:
          dns:
            - api.dashboard.dev.trusted-platform.io
            - vhost1.dashboard.dev.trusted-platform.io
            - vhost2.dashboard.dev.trusted-platform.io
          email:
            - hostmaster@dashboard.dev.trusted-platform.io

    # Virtual Host for 3 node docker HA cluster running on the client
    - home: cluster01.dev.trusted-platform.io
      index: index.html
      hosts:
        - cluster01.dashboard.dev.trusted-platform.io
        - cluster01.dashboard.dev.trusted-platform.io
      proxy:
        backends:
          - http://172.16.1.10:8080
          - http://172.16.2.10:8080
          - http://172.16.3.10:8080
      key:
        algorithm: ECDSA
        ecc:
          curve: P-256
        signature-algorithm: ECDSA-SHA256
        hash: SHA-256
        store: pkcs8
        password: 123456
        platform-policy: true
        debug: true
      certificate:
        acme:
          challenge: http-01
          renew: 15
          cross-sign:
            directory: https://acme-staging-v02.api.letsencrypt.org/directory
            challenge: http-01
        valid: 365
        subject:
          cn: cluster01.dashboard.dev.trusted-platform.io
          organization: Automate The Things, LLC
          country: US
          province: Kernel
          locality: Hypervisor
          address: 456 Virtual Street
          postal-code: 67890
        sans:
          dns:
            - cluster01.dashboard.dev.trusted-platform.io
          email:
            - hostmaster@cluster01.dashboard.dev.trusted-platform.io


# Argon2 Password Hashing
# https://github.com/P-H-C/phc-winner-argon2
# https://pkg.go.dev/golang.org/x/crypto/argon2
argon2:
  memory: 65536
  iterations: 3
  parallelism: 2
  saltLen: 16
  keyLen: 32
